from __future__ import annotations

import re
import subprocess
from pathlib import Path

from hatchling.builders.hooks.plugin.interface import BuildHookInterface


class CustomBuildHook(BuildHookInterface):
    def initialize(self, version: str, build_data: dict) -> None:
        root = Path(self.root)
        git_hash = _git_hash(root) or _existing_build_hash(root) or "unknown"
        source_build_file = root / "src" / "cadmetrics" / "_build.py"
        if self.target_name == "wheel" and source_build_file.exists():
            return

        generated = root / ".hatch-build" / "cadmetrics" / "_build.py"
        generated.parent.mkdir(parents=True, exist_ok=True)
        generated.write_text(
            "# Generated by hatch_build.py during package build.\n"
            "from __future__ import annotations\n\n"
            f'GIT_HASH = "{git_hash}"\n',
            encoding="utf-8",
        )

        target = "cadmetrics/_build.py" if self.target_name == "wheel" else "src/cadmetrics/_build.py"
        build_data.setdefault("force_include", {})[str(generated)] = target


def _git_hash(root: Path) -> str | None:
    try:
        commit = subprocess.run(
            ["git", "rev-parse", "--short=12", "HEAD"],
            cwd=root,
            check=True,
            capture_output=True,
            text=True,
        ).stdout.strip()
    except Exception:
        return None
    if not commit:
        return None
    if _tracked_worktree_is_dirty(root):
        return f"{commit}-dirty"
    return commit


def _tracked_worktree_is_dirty(root: Path) -> bool:
    try:
        status = subprocess.run(
            ["git", "status", "--porcelain", "--untracked-files=no"],
            cwd=root,
            check=True,
            capture_output=True,
            text=True,
        ).stdout.strip()
    except Exception:
        return False
    return bool(status)


def _existing_build_hash(root: Path) -> str | None:
    build_file = root / "src" / "cadmetrics" / "_build.py"
    try:
        text = build_file.read_text(encoding="utf-8")
    except OSError:
        return None
    match = re.search(r"^GIT_HASH\s*=\s*[\"']([^\"']+)[\"']", text, re.MULTILINE)
    if match is None:
        return None
    value = match.group(1).strip()
    return value if value and value != "unknown" else None
